config/routes.rb
Rails.application.routes.draw do
  
  resources :users, only: [:new, :create, :show, :index]
  resources :tickets, only: [:new, :create, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :assigned, foreign_key: "assigned_id", class_name: "User", optional: true

  def assigned?
    
    !!self.assigned
      
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tickets
  has_many :assigned_tickets, foreign_key: "assigned_id", class_name: "Ticket"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ticket_controller.rb
class TicketController < ApplicationController
  
  def index
    @tickets = Ticket.all 
  end

  def show
    ticket_setter
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  private


  def ticket_setter
    @ticket = Ticket.find_by(id: params[:id])
  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    user_setter
  
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  private

  def user_setter
    @user = User.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TroubleTicketRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ticket/edit.html.erb
<h1>Ticket#edit</h1>
<p>Find me in app/views/ticket/edit.html.erb</p>

app/views/ticket/index.html.erb
<h1> Tickets </h1>
<ul>
    <% @tickets.each do |ticket| %>
        <li><%= link_to ticket.title, ticket_path(ticket) %> - <%= link_to ticket.assigned.username, user_path(ticket.assigned) %> </li> 
    <% end %>
</ul>

app/views/ticket/show.html.erb
<h1><%= @ticket.title %></h1>
<p><%= @ticket.description %></p>
<p> Assigned status: <%= @ticket.assigned? %> </p>

app/views/user/index.html.erb
<h1> Users </h1>
<ul>
    <% @users.each do |user| %>
        <li><%= link_to user.username, user_path(user) %></li>
    <% end %>
</ul>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>